In [1]:
import torch

$a:[batch,channel,length,width]$

### $Indexing$

In [2]:
a = torch.rand(4,3,28,28)

In [3]:
a[0].shape

torch.Size([3, 28, 28])

In [4]:
a[0,0].shape

torch.Size([28, 28])

In [5]:
a[0,0,2,4]

tensor(0.9831)

### $select\space first/last\space N$

In [6]:
a.shape

torch.Size([4, 3, 28, 28])

In [7]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [8]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [9]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [10]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

### $select\space by\space steps$

In [11]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [12]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

### $select\space by\space specific\space index$

In [13]:
a.shape

torch.Size([4, 3, 28, 28])

In [14]:
a.index_select(0,torch.tensor([0,2])).shape

torch.Size([2, 3, 28, 28])

In [15]:
a.index_select(1,torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [16]:
a.index_select(2,torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [17]:
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [18]:
a.shape

torch.Size([4, 3, 28, 28])

In [19]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [20]:
a[0,...].shape

torch.Size([3, 28, 28])

In [21]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [22]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

### $select\space by\space mask$ 

In [23]:
x = torch.randn(3,4)
x

tensor([[-0.5798,  1.8884, -1.5138,  0.4819],
        [ 2.1086, -1.2168,  0.0635,  2.3809],
        [ 0.8980, -0.9256, -1.1818, -0.3602]])

In [24]:
mask = x.ge(0.5)
mask

tensor([[False,  True, False, False],
        [ True, False, False,  True],
        [ True, False, False, False]])

In [25]:
torch.masked_select(x,mask)

tensor([1.8884, 2.1086, 2.3809, 0.8980])

In [26]:
torch.masked_select(x,mask).shape

torch.Size([4])

### $select\space by\space flatten\space index$ 

In [27]:
src = torch.tensor([[4,3,5],[6,7,8]])
src

tensor([[4, 3, 5],
        [6, 7, 8]])

In [28]:
torch.take(src,torch.tensor([0,2,-1]))

tensor([4, 5, 8])