In [1]:
import torch
import numpy as np

### $Import\space from\space numpy$

In [2]:
a = np.array([2,3.3])

In [3]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [4]:
a = np.ones([2,3])

In [5]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### $Import\space from\space list$

In [6]:
torch.tensor([2.,3.2])

tensor([2.0000, 3.2000])

In [7]:
torch.FloatTensor([2.,3.2])

tensor([2.0000, 3.2000])

In [8]:
torch.tensor([[2.,3.2],[1.,22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

### $uninitialized$

In [9]:
torch.empty(1)

tensor([0.])

In [10]:
torch.Tensor(2,3)

tensor([[8.4078e-45, 0.0000e+00, 1.2224e-33],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])

In [11]:
torch.IntTensor(2,3)

tensor([[ 875586915,  761410353, 1647456562],
        [ 895890477,  878849335,  925720887]], dtype=torch.int32)

In [12]:
torch.FloatTensor(2,3)

tensor([[0.0000e+00, 8.5899e+09, 4.0779e-16],
        [2.5250e-29, 1.1210e-44, 0.0000e+00]])

### $set\space default\space type$

In [13]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

In [14]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [15]:
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

### $rand/rand\_like/randint$

$rand$ [0,1]

$rand\_like$ 

$randint$ [min,max)

In [16]:
torch.rand(3,3)

tensor([[0.2391, 0.0381, 0.3084],
        [0.2219, 0.3912, 0.0400],
        [0.7647, 0.3567, 0.2421]])

In [17]:
a = torch.rand(3,3)
torch.rand_like(a)

tensor([[0.9550, 0.5239, 0.1771],
        [0.1212, 0.5536, 0.0974],
        [0.2355, 0.7934, 0.2087]])

In [18]:
# [min,max),shape
torch.randint(1,10,(3,3))

tensor([[1, 4, 9],
        [2, 2, 3],
        [6, 5, 5]])

In [19]:
torch.randn(3,3)

tensor([[ 0.5493,  0.4956,  2.0894],
        [ 0.1594, -0.6216, -0.3739],
        [-1.1280,  0.3375, -1.1689]])

In [20]:
torch.normal(mean = torch.full([10],0),std = torch.arange(1,0,-0.1))

../aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([-0.1762,  0.4219, -0.4219, -0.1499,  0.6710,  0.3994,  0.3899,  0.1015,
        -0.1378, -0.0990])

### $full$

In [21]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [22]:
# scalar
torch.full([],7)

tensor(7.)

In [23]:
# vector
torch.full([1],7)

tensor([7.])

### $arange/range$

In [24]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [26]:
# torch.range ❌

### $linspace/logspace$

In [27]:
torch.linspace(0,10,steps = 4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [28]:
torch.linspace(0,10,steps = 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [29]:
torch.linspace(0,10,steps = 11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.logspace(0,-1,steps = 10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [31]:
torch.logspace(0,1,steps = 10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

### $ones/zeros/eye$

In [32]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [35]:
a = torch.zeros(3,3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### $randperm$

In [36]:
torch.randperm(10)

tensor([6, 5, 0, 9, 4, 2, 3, 1, 8, 7])

In [37]:
a = torch.rand(2,3)
a


tensor([[0.3193, 0.6492, 0.1470],
        [0.1394, 0.8079, 0.2504]])

In [38]:
b = torch.rand(2,2)
b

tensor([[0.8084, 0.7770],
        [0.9997, 0.3243]])

In [39]:
idx = torch.randperm(2)
idx

tensor([0, 1])

In [40]:
a[idx]

tensor([[0.3193, 0.6492, 0.1470],
        [0.1394, 0.8079, 0.2504]])

In [41]:
b[idx]

tensor([[0.8084, 0.7770],
        [0.9997, 0.3243]])