In [1]:
import torch

## $Tensor\space advanced\space operation$

- $where$

- $gather$

### $where$

In [2]:
cond = torch.rand(2,2)
a = torch.zeros(2,2)
b = torch.ones(2,2)

In [3]:
cond

tensor([[0.3425, 0.1649],
        [0.1276, 0.6379]])

In [4]:
a

tensor([[0., 0.],
        [0., 0.]])

In [5]:
b

tensor([[1., 1.],
        [1., 1.]])

In [6]:
torch.where(cond > 0.5,a,b)

tensor([[1., 1.],
        [1., 0.]])

### $gather$

In [7]:
prob = torch.rand(4,10)

In [8]:
idx = prob.topk(k = 3,dim = 1)

In [9]:
idx

torch.return_types.topk(
values=tensor([[0.8495, 0.8379, 0.6946],
        [0.8304, 0.7663, 0.6607],
        [0.9967, 0.8661, 0.7777],
        [0.9264, 0.9117, 0.8181]]),
indices=tensor([[7, 8, 1],
        [2, 9, 1],
        [6, 3, 7],
        [2, 1, 6]]))

In [10]:
idx = idx[1]

In [11]:
idx

tensor([[7, 8, 1],
        [2, 9, 1],
        [6, 3, 7],
        [2, 1, 6]])

In [12]:
label = torch.arange(10) + 100

In [13]:
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [14]:
torch.gather(label.expand(4,10),dim = 1,index = idx.long())

tensor([[107, 108, 101],
        [102, 109, 101],
        [106, 103, 107],
        [102, 101, 106]])