In [1]:
import torch

## $Math\space operation$

- $basic=$$Add/minus/multiply/divide$

- $Matmul$

- $Pow$

- $Sqrt/rsqrt$

- $Round$

### $basic$

In [2]:
# 广播机制
a = torch.rand(3,4)
b = torch.rand(4)

In [3]:
a

tensor([[0.3809, 0.3562, 0.5813, 0.6904],
        [0.9548, 0.3884, 0.6759, 0.5215],
        [0.0612, 0.6591, 0.9008, 0.2450]])

In [4]:
b

tensor([0.2089, 0.4991, 0.1496, 0.5553])

In [5]:
a + b

tensor([[0.5898, 0.8552, 0.7309, 1.2457],
        [1.1637, 0.8874, 0.8255, 1.0768],
        [0.2701, 1.1581, 1.0504, 0.8003]])

In [6]:
torch.add(a,b)

tensor([[0.5898, 0.8552, 0.7309, 1.2457],
        [1.1637, 0.8874, 0.8255, 1.0768],
        [0.2701, 1.1581, 1.0504, 0.8003]])

In [7]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

In [8]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [9]:
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(True)

### $matmul$

- $Torch.mm$ 不推荐，只适用于2维

- $Torch.matmul$ 推荐

- $@$

In [10]:
a = torch.ones(2,2) * 3

In [11]:
a

tensor([[3., 3.],
        [3., 3.]])

In [12]:
b = torch.ones(2,2)

In [13]:
b

tensor([[1., 1.],
        [1., 1.]])

In [14]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [15]:
torch.matmul(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [16]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [17]:
# An example

In [18]:
a = torch.rand(4,784)
x = torch.rand(4,784)
w = torch.rand(512,784)

In [19]:
(x@w.t()).shape

torch.Size([4, 512])

In [20]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)

$Error$

```python
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)
torch.mm(a,b).shape

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-18c616c4b668> in <module>
----> 1 torch.mm(a,b).shape

RuntimeError: matrices expected, got 4D, 4D tensors at ../aten/src/TH/generic/THTensorMath.cpp:36
```

In [21]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [22]:
b = torch.rand(4,1,64,32)

In [23]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

$Error$

```python
a = torch.rand(4,3,28,64)
b = torch.rand(6,64,32)
torch.matmul(a,b).shape

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-6259b28e956d> in <module>
      1 b = torch.rand(6,64,32)
----> 2 torch.matmul(a,b).shape

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1

```

### $pow$

In [24]:
a = torch.full([2,2],3)

../aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


In [25]:
a

tensor([[3., 3.],
        [3., 3.]])

In [26]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [27]:
a**2

tensor([[9., 9.],
        [9., 9.]])

In [28]:
aa = a**2

### $sqrt/rsqrt$

In [29]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [30]:
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [31]:
aa ** 0.5

tensor([[3., 3.],
        [3., 3.]])

### $Exp/log$

In [32]:
a = torch.exp(torch.ones(2,2))

In [33]:
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [34]:
torch.log(a)

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]])

### $Approximation$

- $.floor() .ceil()$
- $.round()$
- $.trunc() .frac()$

In [35]:
a = torch.tensor(3.14)

In [36]:
a.floor()

tensor(3.)

In [37]:
a.ceil()

tensor(4.)

In [38]:
a.trunc()

tensor(3.)

In [39]:
a.frac()

tensor(0.1400)

In [40]:
a = torch.tensor(3.499)

In [41]:
a.round()

tensor(3.)

In [42]:
a = torch.tensor(3.5)

In [43]:
a.round()

tensor(4.)

### $clamp$

In [44]:
grad = torch.rand(2,3) * 15

In [45]:
grad.max()

tensor(11.3671)

In [46]:
grad.median()

tensor(7.6886)

In [47]:
grad.clamp(10)

tensor([[10.0000, 10.0000, 11.2718],
        [10.0000, 10.0000, 11.3671]])

In [48]:
grad

tensor([[ 7.6886,  0.3353, 11.2718],
        [ 5.2982,  7.9627, 11.3671]])

In [49]:
grad.clamp(0,10)

tensor([[ 7.6886,  0.3353, 10.0000],
        [ 5.2982,  7.9627, 10.0000]])