## 数据类型

<img src="./images/l5_datatype.png" width=520, heigth=240/>

In [1]:
import torch
import numpy as np

### $Type\space check$

In [2]:
a = torch.randn(2,3)

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a,torch.FloatTensor)

True

### $Dimension\space 0/rank\space 0$

In [6]:
torch.tensor(1.)

tensor(1.)

In [7]:
torch.tensor(1.3)

tensor(1.3000)

In [8]:
a = torch.tensor(2.2)

In [9]:
a.shape

torch.Size([])

In [10]:
len(a.shape)

0

In [11]:
a.size()

torch.Size([])

### $Dimension\space 1/rank\space 1$

In [12]:
torch.tensor([1.1])

tensor([1.1000])

In [13]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [14]:
torch.FloatTensor(1)

tensor([-1.0842e-19])

In [15]:
torch.FloatTensor(2)

tensor([ 0.0000e+00, -4.6566e-10])

In [16]:
data = np.ones(2)

In [17]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [18]:
a = torch.ones(2)

In [19]:
a.shape

torch.Size([2])

### $Dimension\space 2/rank\space 2$

In [20]:
a = torch.randn(2,3)

In [21]:
a

tensor([[-1.6328, -0.5419,  0.0893],
        [ 2.0313, -0.9870, -1.7296]])

In [22]:
a.shape

torch.Size([2, 3])

In [23]:
a.size(0)

2

In [24]:
a.size(1)

3

In [25]:
a.shape[1]

3

### $Dimension\space 3/rank\space 3$

In [26]:
a = torch.rand(1,2,3)

In [27]:
a

tensor([[[0.1195, 0.5281, 0.7723],
         [0.9338, 0.3176, 0.5968]]])

In [28]:
a.shape

torch.Size([1, 2, 3])

In [29]:
a[0]

tensor([[0.1195, 0.5281, 0.7723],
        [0.9338, 0.3176, 0.5968]])

In [30]:
list(a.shape)

[1, 2, 3]

### $Dimension\space 4/rank\space 4$

In [31]:
a = torch.randn(1,3,28,28)

In [32]:
a

tensor([[[[-1.7189e+00, -5.6872e-01,  7.7049e-01,  ...,  1.5119e+00,
            3.1021e-01,  2.1173e-01],
          [-8.5715e-02, -3.2469e-01,  9.7485e-01,  ...,  5.0102e-01,
           -2.3665e-01,  1.7643e-01],
          [ 4.9575e-01,  2.0616e-01, -3.5179e-01,  ...,  2.0372e+00,
            9.2504e-01,  5.0461e-01],
          ...,
          [ 6.3258e-01, -1.5194e+00,  1.4093e+00,  ...,  1.1387e+00,
           -1.7393e-01, -8.5882e-01],
          [ 7.9191e-01,  1.8335e+00, -8.5870e-01,  ...,  7.1985e-01,
            7.8601e-02,  1.0362e+00],
          [ 2.1861e+00,  1.5007e+00,  1.1123e+00,  ...,  4.6003e-01,
            1.1900e-01,  1.1418e+00]],

         [[ 8.1494e-01,  2.3965e-01, -2.7545e-02,  ...,  1.0914e+00,
            1.4880e+00,  1.3620e+00],
          [ 1.5134e-02,  8.5962e-01,  1.0859e+00,  ...,  8.0951e-01,
            1.9455e-01, -3.4033e-01],
          [ 7.8168e-01,  1.7680e+00, -1.2592e-01,  ..., -6.7520e-01,
           -5.0420e-01,  1.7030e-01],
          ...,
     

In [33]:
a.shape

torch.Size([1, 3, 28, 28])

### $Mixed$

In [34]:
a.shape

torch.Size([1, 3, 28, 28])

In [35]:
# 占内存大小
a.numel()

2352

In [36]:
# 返回长度
a.dim()

4