In [1]:
import torch

## $Operation$

- $View/reshape$

- $Squeeze/unsqueez$

- $Transpose/t/permute$

- $Expand/repeat$

### $View/reshape$

view与reshape用法一致

In [2]:
a = torch.rand(4,1,28,28)

In [3]:
a.shape

torch.Size([4, 1, 28, 28])

In [4]:
a.view(4,28*28)

tensor([[0.3119, 0.5369, 0.0716,  ..., 0.5901, 0.9709, 0.0840],
        [0.1729, 0.7027, 0.0882,  ..., 0.2998, 0.8972, 0.1559],
        [0.6869, 0.0621, 0.2235,  ..., 0.8772, 0.4899, 0.0951],
        [0.8927, 0.9689, 0.1014,  ..., 0.0775, 0.7951, 0.6934]])

In [5]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [6]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [7]:
b = a.view(4,784)

In [8]:
b.view(4,28,28,1)

tensor([[[[0.3119],
          [0.5369],
          [0.0716],
          ...,
          [0.5125],
          [0.3057],
          [0.3563]],

         [[0.8348],
          [0.7512],
          [0.9818],
          ...,
          [0.1726],
          [0.8497],
          [0.4243]],

         [[0.3056],
          [0.6513],
          [0.2643],
          ...,
          [0.7487],
          [0.5109],
          [0.2359]],

         ...,

         [[0.3518],
          [0.4315],
          [0.5921],
          ...,
          [0.1585],
          [0.3224],
          [0.5723]],

         [[0.6915],
          [0.4568],
          [0.0224],
          ...,
          [0.1167],
          [0.2481],
          [0.9820]],

         [[0.5990],
          [0.5162],
          [0.6277],
          ...,
          [0.5901],
          [0.9709],
          [0.0840]]],


        [[[0.1729],
          [0.7027],
          [0.0882],
          ...,
          [0.2586],
          [0.9070],
          [0.9555]],

         [[0.0897],
    

In [9]:
b.view(4,28,28,1).shape

torch.Size([4, 28, 28, 1])

### $Squeeze/unsqueeze$

$unsqueeze$

In [10]:
a.shape

torch.Size([4, 1, 28, 28])

In [11]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [12]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [13]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [14]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [15]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

```python
a.unsqueeze(5).shape

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-23-b54eab361a50> in <module>
----> 1 a.unsqueeze(5).shape

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)
```

##### $unsqueeze:$

<img src ='./images/l8_unsqueeze.png' width=300/>

In [16]:
a = torch.tensor([1.2,2.3])
a

tensor([1.2000, 2.3000])

In [17]:
a.shape

torch.Size([2])

In [18]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [19]:
a.shape

torch.Size([2])

In [20]:
# For example
b = torch.rand(32)
f = torch.rand(4,32,14,14)

In [21]:
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)

In [22]:
b.shape

torch.Size([1, 32, 1, 1])

$squeeze$

In [23]:
b.shape

torch.Size([1, 32, 1, 1])

In [24]:
b.squeeze().shape

torch.Size([32])

In [25]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [26]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [27]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [28]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

### $Expand/repeat$

$Expand:broadcasting$

$Repeat:memory\space copied$

In [29]:
a = torch.rand(4,32,14,14)

In [30]:
# expand
b.shape

torch.Size([1, 32, 1, 1])

In [31]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [32]:
b.expand(-1,32,-1,-1).shape

torch.Size([1, 32, 1, 1])

In [33]:
b.expand(-1,32,-1,-4).shape

torch.Size([1, 32, 1, -4])

In [34]:
# repeat
b.shape

torch.Size([1, 32, 1, 1])

In [35]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [36]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [37]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

### $Transpose/t/permute$

$t$

In [38]:
a = torch.randn(3,4)
a

tensor([[ 1.2431,  0.5581,  0.9412,  2.0231],
        [-0.8447, -0.4017, -0.1193,  0.6983],
        [-2.4136,  0.7061, -0.6122,  0.6539]])

In [39]:
a.t()

tensor([[ 1.2431, -0.8447, -2.4136],
        [ 0.5581, -0.4017,  0.7061],
        [ 0.9412, -0.1193, -0.6122],
        [ 2.0231,  0.6983,  0.6539]])

$transpose$

In [40]:
a = torch.randn(4,3,32,32)

In [41]:
a.shape

torch.Size([4, 3, 32, 32])

```python
a1 = a.transpose(1,3).view(4,3*32*32).view(4,3,32,32)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-74-262e84a7fdcb> in <module>
----> 1 a1 = a.transpose(1,3).view(4,3*32*32).view(4,3,32,32)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

In [42]:
# 正确做法
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)

In [43]:
a1.shape,a2.shape

(torch.Size([4, 3, 32, 32]), torch.Size([4, 3, 32, 32]))

In [44]:
torch.all(torch.eq(a,a1))

tensor(False)

In [45]:
torch.all(torch.eq(a,a2))

tensor(True)

$permute$

In [46]:
a = torch.rand(4,3,28,28)

In [47]:
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [48]:
b = torch.rand(4,3,28,32)

In [49]:
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [50]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [51]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])