### $Feature\space scaling$

- $Image\space Normalization$

```python
normalize = transforms.Normalize(mean = [0.485,0.456,0.406],
                      std = [0.229,0.224,0.225])
```
#### $Batch\space Normalization$ 

- $Batch\space Norm$

- $Layer\space Norm$

- $Instance\space Norm$

- $Group\space Norm$

<img src='./images/l36_batch_norm.png' width = 400 />

In [1]:
# Batch = [N,C,H,W]

In [2]:
import torch 
import torch.nn as nn

In [3]:
# U(0.5,1)
x = torch.rand(100,16,784)
# Channels
layer = nn.BatchNorm1d(16)
out = layer(x)

In [4]:
layer.running_mean

tensor([0.0500, 0.0501, 0.0500, 0.0499, 0.0500, 0.0498, 0.0499, 0.0499, 0.0499,
        0.0499, 0.0500, 0.0499, 0.0500, 0.0499, 0.0500, 0.0500])

In [5]:
layer.running_var

tensor([0.9083, 0.9083, 0.9084, 0.9083, 0.9084, 0.9084, 0.9083, 0.9084, 0.9083,
        0.9083, 0.9083, 0.9083, 0.9084, 0.9084, 0.9083, 0.9083])

$nn.BatchNorm2d$

In [6]:
x = torch.rand(1,16,7,7)
x.shape

torch.Size([1, 16, 7, 7])

In [7]:
layer = nn.BatchNorm2d(16)

In [8]:
out = layer(x)
out.shape

torch.Size([1, 16, 7, 7])

In [9]:
layer.weight

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)

In [10]:
layer.weight.shape

torch.Size([16])

In [11]:
layer.bias.shape

torch.Size([16])

In [12]:
vars(layer)

{'training': True,
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0488, 0.0478, 0.0453, 0.0476, 0.0504, 0.0503, 0.0498, 0.0502, 0.0482,
                       0.0465, 0.0455, 0.0472, 0.0501, 0.0483, 0.0431, 0.0442])),
              ('running_var',
               tensor([0.9084, 0.9087, 0.9098, 0.9062, 0.9088, 0.9086, 0.9077, 0.9085, 0.9069,
                       0.9075, 0.9072, 0.9100, 0.9073, 0.9078, 0.9065, 0.9097])),
              ('num_batches_tracked', tensor(1))]),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_forward_hooks': OrderedDict(),
 '_for