In [1]:
import torch

## $statistics$

- $norm$
- $mean\space sum$
- $prod$
- $max/min/argmin/argmax$
- $kthvalue/topk$

### $norm$

In [2]:
a = torch.full([8],1)

../aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


In [3]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
b = a.view(2,4)
c = a.view(2,2,2)

In [5]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [7]:
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [8]:
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [9]:
b.norm(1,dim = 1)

tensor([4., 4.])

In [10]:
b.norm(2,dim = 1)

tensor([2., 2.])

In [11]:
c.norm(1,dim = 0)

tensor([[2., 2.],
        [2., 2.]])

In [12]:
c.norm(2,dim = 0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

### $mean/sum/min/max/prod$

In [13]:
a = torch.arange(8).view(2,4).float()

In [14]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [15]:
a.min(),a.max(),a.mean(),a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [16]:
a.sum()

tensor(28.)

In [17]:
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [18]:
a = a.view(1,2,4)

In [19]:
a

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [20]:
a.argmax()

tensor(7)

In [21]:
a.argmin()

tensor(0)

In [22]:
a = torch.rand(2,3,4)

In [23]:
a.argmax()

tensor(17)

In [24]:
a = torch.randn(4,10)

In [25]:
a[0]

tensor([-1.8121, -0.2583, -1.1174,  0.9105,  0.2644,  1.0182, -0.2978, -0.0099,
         0.4411, -0.3536])

In [26]:
a.argmax()

tensor(37)

In [27]:
a.argmax(dim = 1)

tensor([5, 5, 4, 7])

### $dim,keepdim$

In [28]:
a = torch.rand(4,10)

In [29]:
a.shape

torch.Size([4, 10])

In [30]:
a.max(dim = 1)

torch.return_types.max(
values=tensor([0.8738, 0.9971, 0.8623, 0.9780]),
indices=tensor([9, 5, 5, 3]))

In [31]:
a.argmax(dim = 1)

tensor([9, 5, 5, 3])

In [32]:
a.max(dim = 1,keepdim = True)

torch.return_types.max(
values=tensor([[0.8738],
        [0.9971],
        [0.8623],
        [0.9780]]),
indices=tensor([[9],
        [5],
        [5],
        [3]]))

In [33]:
a.argmax(dim = 1,keepdim = True)

tensor([[9],
        [5],
        [5],
        [3]])

### $top-k/k-th$

In [34]:
a = torch.rand(4,10)

In [35]:
a.shape

torch.Size([4, 10])

In [36]:
a.topk(3,dim = 1)

torch.return_types.topk(
values=tensor([[0.9999, 0.9809, 0.9776],
        [0.8233, 0.6239, 0.5821],
        [0.9214, 0.9111, 0.9012],
        [0.9411, 0.8931, 0.7642]]),
indices=tensor([[2, 7, 3],
        [5, 0, 7],
        [8, 6, 2],
        [7, 4, 6]]))

In [37]:
a.topk(3,dim = 1,largest = False)

torch.return_types.topk(
values=tensor([[0.0544, 0.2615, 0.3609],
        [0.0274, 0.2457, 0.3315],
        [0.0888, 0.2861, 0.2964],
        [0.0399, 0.1151, 0.1451]]),
indices=tensor([[4, 8, 5],
        [9, 4, 3],
        [5, 4, 9],
        [9, 5, 0]]))

In [38]:
a.kthvalue(8,dim = 1)

torch.return_types.kthvalue(
values=tensor([0.9776, 0.5821, 0.9012, 0.7642]),
indices=tensor([3, 7, 2, 6]))

In [39]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([0.3609, 0.3315, 0.2964, 0.1451]),
indices=tensor([5, 3, 9, 0]))

In [40]:
a.kthvalue(3,dim = 1)

torch.return_types.kthvalue(
values=tensor([0.3609, 0.3315, 0.2964, 0.1451]),
indices=tensor([5, 3, 9, 0]))

### $compare$

In [41]:
a = torch.rand(4,10)

In [42]:
a 

tensor([[0.0609, 0.1727, 0.0142, 0.2369, 0.3778, 0.7469, 0.6207, 0.9854, 0.6959,
         0.5522],
        [0.9801, 0.0474, 0.1057, 0.6555, 0.3157, 0.0457, 0.8043, 0.3107, 0.8217,
         0.5269],
        [0.0185, 0.7971, 0.8014, 0.1377, 0.8241, 0.9090, 0.4190, 0.1013, 0.1150,
         0.4935],
        [0.2113, 0.9133, 0.1807, 0.2687, 0.0916, 0.8177, 0.5691, 0.8005, 0.4711,
         0.4109]])

In [43]:
a > 0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [44]:
torch.gt(a,0)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [45]:
a!=0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [46]:
a = torch.ones(2,3)
b = torch.randn(2,3) 

In [47]:
torch.eq(a,b)

tensor([[False, False, False],
        [False, False, False]])

In [48]:
torch.eq(a,a)

tensor([[True, True, True],
        [True, True, True]])